feat: chainsaws
CraftoryStudios/Craftory-Tech pull request #134
Opened 2021-09-15 20:50 UTC by MMJ744

- Added chainsaws
- Fixed Pom
- Removed bad lang files

2021-09-20 23:06 UTC, brettsaunders21 requested changes

2021-09-20 23:06 UTC, brettsaunders21 commented on src/main/java/tech/brettsaunders/craftory/tech/power/core/tools/Chainsaw.java
> +        if (chainsawBlocks.contains(block.getType()) && charge >= TOOL_POWER_COST) {
Can't these two if's be combined?

2021-09-20 23:06 UTC, brettsaunders21 commented on src/main/java/tech/brettsaunders/craftory/tech/power/core/tools/PoweredToolManager.java
> +    if(charge < TOOL_POWER_COST && event.getPlayer().getGameMode()!=GameMode.CREATIVE) {
```suggestion
    if(charge < TOOL_POWER_COST && event.getPlayer().getGameMode() != GameMode.CREATIVE) {
```

2021-09-20 23:13 UTC, MMJ744 commented on src/main/java/tech/brettsaunders/craftory/tech/power/core/tools/Chainsaw.java
> +        if (chainsawBlocks.contains(block.getType()) && charge >= TOOL_POWER_COST) {
Yes they can be. They were separate because of the shared logic with the other tools, should probably make them generic, lots of code re-use. 

Tempted to keep them separate to make sure the permission check isn't lost if changes are made in the future. But I suppose combining them would be more inline with the code formatting standards.

2021-10-04 17:31 UTC, brettsaunders21 approved these changes

2021-10-04 17:31 UTC, merged