fix(core-blocks): magnetising table and rotary generator fixes
CraftoryStudios/Craftory-Tech pull request #176
Opened 2022-01-04 16:33 UTC by kamrantekkit

fix(MagnestisingTable): Bug fix for duplication issue when Table's chunk is unloaded and loaded as well on server stop/start.

fix(Rotary-Generator): Improved code of the ChunkLoad Handler. As before was causing rapid chunk loading calls to the rotary gen's chunk

2022-01-04 22:05 UTC, brettsaunders21 requested changes

2022-01-04 22:05 UTC, brettsaunders21 commented on src/main/java/tech/brettsaunders/craftory/tech/power/core/block/machine/magnetiser/MagnetisingTable.java
> +            System.out.println(frameItem);
Please remove this debug line

2022-01-04 22:10 UTC, brettsaunders21 commented
Also version needs updating to v0.8.2

2022-01-04 22:19 UTC, kamrantekkit commented
My bad, I corrected them now

2022-01-06 00:28 UTC, brettsaunders21 approved these changes
Looks good

2022-01-06 21:20 UTC, merged